[package]
name = "godot-vlc"
version = "1.1.1"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = {version = "0.3.5", features = ["experimental-threads", "register-docs", "api-4-3"]}
printf = "0.1.0"
ringbuf = "0.4.8"

[build-dependencies]
bindgen = "0.72.1"
